name: Check Dead Links

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check dead links
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '**/*.md' --exclude-mail
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Dead links detected
          content-filepath: ./lychee/out.md
          labels: |
            bug
            dead-links
          assignees: ${{ github.repository_owner }}
